import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather Next API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Weather API! get any city wheater forecast data through REST API methods
        </h1>

        <p className={styles.description}>
          <Link href="/endpoints">
            <a>
              Get started by looking the{" "}
              <code className={styles.code}>endpoints</code>
            </a>
          </Link>
        </p>
      </main>
    </div>
  );
}
